### ISSUE TITLE
how to install the components on a new project?

### ISSUE THREAD

**Issue by m1guer** [huacnlee/gpui-component#52]
hi, im trying to use the components but im a little bit confused.

how to install?

**Comment by huacnlee** [comment]
Just add gpui and ui into your Cargo.toml

```toml
[dependencies]
ui = { git = "https://github.com/huacnlee/gpui-component.git" }
gpui = { git = "https://github.com/huacnlee/zed.git", branch = "export-platform-window" }
```

Currently, need use `huacnlee/zed` fork, because it includes WebView support API for GPUI.
